spring.application.name=gestion-suivi-evaluation-service
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_suivi_evaluation_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=VUFZWjIwMjZTdXBlclNlY3VyZUpXVEtleUZvckF1dGhlbnRpY2F0aW9uU3lzdGVtMTIzNDU2
jwt.expiration=86400000

services.encadrement.url=http://localhost:8083/api
services.livrable.url=http://localhost:8084/api